name: flippy_pairs
description: "Flippy Pairs Project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  synchronized: ^3.1.0+1
  http: ^1.5.0
  audioplayers: ^6.5.1
  supabase_flutter: ^2.10.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  path_provider: ^2.1.2
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/imagenes/app_logo.png

flutter_native_splash:
  color: "#3A4BA7"
  image: assets/imagenes/app_splash.png
  android: true
  ios: false
  android_12:
    color: "#3A4BA7"
    image: assets/imagenes/app_splash.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/sonidos/
